### ISSUE TITLE
Error en versiones illuminate/support

### ISSUE THREAD

**Issue by alexramdesigner** [miguelgarces123/consultas-rues#1]
@miguelgarces123 intente instalar el paquete pero me sale el siguiente error:

`Problem 1
- Root composer.json requires miguelgarces/consultas-rues ^1.0 -> satisfiable by miguelgarces/consultas-rues[v1.0.0].
- miguelgarces/consultas-rues v1.0.0 requires illuminate/support ^5.5|^6|^7|^8 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require miguelgarces/consultas-rues:*" to figure out if any version is installable, or "composer require miguelgarces/consultas-rues:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

**Comment by miguelgarces123** [comment]
Hola @alexramdesigner , segun veo el error el conflicto es con illuminate/support el cual es el que utilizo para determinar la versión compatible de Laravel.

Que versión de Laravel estas usando ?
